# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.19"
  amd64: "ghcr.io/home-assistant/amd64-base:3.19"
  armhf: "ghcr.io/home-assistant/armhf-base:3.19"
  armv7: "ghcr.io/home-assistant/armv7-base:3.19"
  i386: "ghcr.io/home-assistant/i386-base:3.19"
labels:
  org.opencontainers.image.title: "1Password for Home Assistant"
  org.opencontainers.image.description: "Sync your secrets from 1password"
  org.opencontainers.image.source: "https://github.com/Borales/hassio-1password-addon"
  org.opencontainers.image.licenses: "MIT License"
