name: TEMP

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NEXT_TELEMETRY_DISABLED: 1
  NODE_ENV: production

jobs:
  init:
    runs-on: ubuntu-latest
    name: Initialize builds
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: yarn install
        working-directory: ./hassio-1password-addon/web
      - run: yarn build
        working-directory: ./hassio-1password-addon/web
